# Generated by Django 5.0.7 on 2024-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallerInsight', '0002_alter_contact_email_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
