# Generated by Django 5.0.7 on 2024-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallerInsight', '0004_matchusercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
